const { expect } = require("chai");
const { ethers } = require("hardhat");

describe("Web3NFT Contract", function () {
  let web3NFT;
  let owner;
  let addr1;
  let addr2;

  const TOKEN_NAME = "Web3 AI Agent NFT";
  const TOKEN_SYMBOL = "W3AI";

  beforeEach(async function () {
    [owner, addr1, addr2] = await ethers.getSigners();

    const Web3NFT = await ethers.getContractFactory("Web3NFT");
    web3NFT = await Web3NFT.deploy();
    await web3NFT.waitForDeployment();
  });

  describe("部署", function () {
    it("应该设置正确的名称和符号", async function () {
      expect(await web3NFT.name()).to.equal(TOKEN_NAME);
      expect(await web3NFT.symbol()).to.equal(TOKEN_SYMBOL);
    });

    it("应该设置正确的所有者", async function () {
      expect(await web3NFT.owner()).to.equal(owner.address);
    });

    it("初始供应量应该为0", async function () {
      expect(await web3NFT.totalSupply()).to.equal(0);
    });
  });

  describe("铸造NFT", function () {
    it("所有者应该能够铸造NFT", async function () {
      const uri = "ipfs://QmTest123";

      const tx = await web3NFT.mintNFT(addr1.address, uri, false);
      const receipt = await tx.wait();

      const tokenId = 0;

      expect(await web3NFT.ownerOf(tokenId)).to.equal(addr1.address);
      expect(await web3NFT.tokenURI(tokenId)).to.equal(uri);
      expect(await web3NFT.totalSupply()).to.equal(1);

      // 检查事件
      await expect(web3NFT.mintNFT(addr1.address, uri, false))
        .to.emit(web3NFT, "NFTMinted")
        .withArgs(tokenId + 1, addr1.address, uri, false);
    });

    it("应该正确设置AI生成标记", async function () {
      const uri = "ipfs://QmAI456";

      await web3NFT.mintNFT(addr1.address, uri, true);
      const tokenId = 0;

      expect(await web3NFT.isAIGenerated(tokenId)).to.equal(true);
    });

    it("非所有者不应该能够铸造NFT", async function () {
      const uri = "ipfs://QmTest789";

      await expect(
        web3NFT.connect(addr1).mintNFT(addr2.address, uri, false)
      ).to.be.revertedWithCustomError(web3NFT, "OwnableUnauthorizedAccount");
    });

    it("应该自动递增tokenId", async function () {
      const uri1 = "ipfs://QmTest1";
      const uri2 = "ipfs://QmTest2";

      await web3NFT.mintNFT(addr1.address, uri1, false);
      await web3NFT.mintNFT(addr2.address, uri2, false);

      expect(await web3NFT.totalSupply()).to.equal(2);
      expect(await web3NFT.ownerOf(0)).to.equal(addr1.address);
      expect(await web3NFT.ownerOf(1)).to.equal(addr2.address);
    });
  });

  describe("批量铸造", function () {
    it("所有者应该能够批量铸造NFT", async function () {
      const uris = [
        "ipfs://QmTest1",
        "ipfs://QmTest2",
        "ipfs://QmTest3"
      ];

      const tx = await web3NFT.batchMintNFT(addr1.address, uris);
      const receipt = await tx.wait();

      expect(await web3NFT.totalSupply()).to.equal(3);
      expect(await web3NFT.balanceOf(addr1.address)).to.equal(3);
    });

    it("非所有者不应该能够批量铸造", async function () {
      const uris = ["ipfs://QmTest1"];

      await expect(
        web3NFT.connect(addr1).batchMintNFT(addr2.address, uris)
      ).to.be.revertedWithCustomError(web3NFT, "OwnableUnauthorizedAccount");
    });
  });

  describe("元数据管理", function () {
    it("应该能够更新元数据", async function () {
      const uri = "ipfs://QmTest123";
      await web3NFT.mintNFT(addr1.address, uri, false);

      const tokenId = 0;
      const name = "AI Art #1";
      const description = "Generated by AI";

      await web3NFT.updateMetadata(tokenId, name, description);

      const info = await web3NFT.getNFTInfo(tokenId);
      expect(info.name).to.equal(name);
      expect(info.description).to.equal(description);
    });

    it("应该能够获取完整的NFT信息", async function () {
      const uri = "ipfs://QmTest123";
      await web3NFT.mintNFT(addr1.address, uri, true);

      const tokenId = 0;
      const info = await web3NFT.getNFTInfo(tokenId);

      expect(info.id).to.equal(BigInt(tokenId));
      expect(info.owner).to.equal(addr1.address);
      expect(info.uri).to.equal(uri);
      expect(info.aiGen).to.equal(true);
      expect(info.power).to.equal(BigInt(1));
    });
  });

  describe("投票权管理", function () {
    it("应该设置默认投票权为1", async function () {
      const uri = "ipfs://QmTest123";
      await web3NFT.mintNFT(addr1.address, uri, false);

      const tokenId = 0;
      expect(await web3NFT.votingPower(tokenId)).to.equal(1);
    });

    it("所有者应该能够设置投票权", async function () {
      const uri = "ipfs://QmTest123";
      await web3NFT.mintNFT(addr1.address, uri, false);

      const tokenId = 0;
      const newPower = 5;

      await web3NFT.setVotingPower(tokenId, newPower);
      expect(await web3NFT.votingPower(tokenId)).to.equal(newPower);
    });
  });

  describe("查询功能", function () {
    it("应该能够获取账户拥有的所有NFT", async function () {
      const uris = [
        "ipfs://QmTest1",
        "ipfs://QmTest2",
        "ipfs://QmTest3"
      ];

      await web3NFT.batchMintNFT(addr1.address, [uris[0]]);
      await web3NFT.batchMintNFT(addr2.address, [uris[1], uris[2]]);

      const addr1NFTs = await web3NFT.getNFTsByOwner(addr1.address);
      const addr2NFTs = await web3NFT.getNFTsByOwner(addr2.address);

      expect(addr1NFTs.length).to.equal(1);
      expect(addr2NFTs.length).to.equal(2);
      expect(addr1NFTs[0]).to.equal(0);
      expect(addr2NFTs[0]).to.equal(1);
      expect(addr2NFTs[1]).to.equal(2);
    });

    it("应该正确返回余额", async function () {
      const uris = ["ipfs://QmTest1", "ipfs://QmTest2"];

      await web3NFT.batchMintNFT(addr1.address, uris);

      expect(await web3NFT.balanceOf(addr1.address)).to.equal(2);
    });
  });

  describe("转账", function () {
    it("应该能够转账NFT", async function () {
      const uri = "ipfs://QmTest123";
      await web3NFT.mintNFT(addr1.address, uri, false);

      const tokenId = 0;

      await web3NFT.connect(addr1).transferFrom(addr1.address, addr2.address, tokenId);

      expect(await web3NFT.ownerOf(tokenId)).to.equal(addr2.address);
      expect(await web3NFT.balanceOf(addr1.address)).to.equal(0);
      expect(await web3NFT.balanceOf(addr2.address)).to.equal(1);
    });

    it("应该支持授权转账", async function () {
      const uri = "ipfs://QmTest123";
      await web3NFT.mintNFT(addr1.address, uri, false);

      const tokenId = 0;

      await web3NFT.connect(addr1).approve(addr2.address, tokenId);
      await web3NFT.connect(addr2).transferFrom(addr1.address, addr2.address, tokenId);

      expect(await web3NFT.ownerOf(tokenId)).to.equal(addr2.address);
    });
  });

  describe("事件", function () {
    it("应该触发NFTMinted事件", async function () {
      const uri = "ipfs://QmTest123";

      await expect(web3NFT.mintNFT(addr1.address, uri, true))
        .to.emit(web3NFT, "NFTMinted")
        .withArgs(0, addr1.address, uri, true);
    });

    it("应该触发VotingPowerSet事件", async function () {
      const uri = "ipfs://QmTest123";

      await expect(web3NFT.mintNFT(addr1.address, uri, false))
        .to.emit(web3NFT, "VotingPowerSet")
        .withArgs(0, 1);
    });

    it("应该触发MetadataUpdated事件", async function () {
      const uri = "ipfs://QmTest123";
      await web3NFT.mintNFT(addr1.address, uri, false);

      await expect(web3NFT.updateMetadata(0, "Test", "Description"))
        .to.emit(web3NFT, "MetadataUpdated")
        .withArgs(0, "Test", "Description");
    });
  });
});
