/**
 * Deployer Agent - Generates Deployment Scripts for Smart Contracts
 *
 * 功能：
 * - 为合约创建部署脚本
 * - 保存到scripts/目录
 */

const fs = require("fs");
const path = require("path");

class DeployerAgent {
  constructor(hre) {
    this.hre = hre;
    this.scriptsDir = path.join(process.cwd(), "scripts");
  }

  /**
   * 根据计划生成部署脚本
   * @param {object} plan - planner生成的执行计划
   * @returns {object} 生成结果
   */
  async generate(plan) {
    console.log("\n" + "=".repeat(70));
    console.log("🚀 Deployer Agent - Generating Deployment Scripts");
    console.log("=".repeat(70));

    try {
      // 确保scripts目录存在
      this._ensureDir(this.scriptsDir);

      // 根据合约类型生成部署脚本
      const scriptCode = this._generateDeployScript(plan);

      // 保存部署脚本
      const fileName = `deploy-${plan.contractName}.js`;
      const filePath = path.join(this.scriptsDir, fileName);
      fs.writeFileSync(filePath, scriptCode, "utf8");

      console.log(`\n✓ Deployment script generated: ${fileName}`);
      console.log(`  Location: scripts/${fileName}`);
      console.log(`  Size: ${scriptCode.length} bytes`);

      return {
        success: true,
        fileName,
        filePath,
        contractName: plan.contractName,
        code: scriptCode
      };

    } catch (error) {
      console.error(`\n✗ Error generating deployment script: ${error.message}`);
      return {
        success: false,
        error: error.message
      };
    }
  }

  /**
   * 生成部署脚本代码
   * @param {object} plan - 执行计划
   * @returns {string} 部署脚本代码
   */
  _generateDeployScript(plan) {
    const { contractName, type, specifications } = plan;

    // 根据合约类型生成不同的部署脚本
    switch (type) {
      case "ERC20":
        return this._generateERC20Deploy(contractName, specifications);
      case "ERC721":
        return this._generateERC721Deploy(contractName, specifications);
      case "DAO":
        return this._generateDAODeploy(contractName, specifications);
      case "Voting":
        return this._generateVotingDeploy(contractName, specifications);
      default:
        return this._generateGenericDeploy(contractName);
    }
  }

  /**
   * 生成ERC20部署脚本
   */
  _generateERC20Deploy(name, specs = {}) {
    const args = this._getConstructorArgs(name, specs, "ERC20");

    return `const hre = require("hardhat");

/**
 * Deployment script for ${name}
 * Generated by Web3 AI Agent
 *
 * Usage: npx hardhat run scripts/deploy-${name}.js --network <network>
 */
async function main() {
  console.log("Deploying ${name}...");

  // Get deployer account
  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying contracts with account:", deployer.address);
  console.log("Account balance:", (await hre.ethers.provider.getBalance(deployer.address)).toString());

  // Deploy contract
  const ${this._camelCase(name)} = await hre.ethers.deployContract("${name}"${args});

  await ${this._camelCase(name)}.waitForDeployment();
  const address = await ${this._camelCase(name)}.getAddress();

  console.log("\\n✅ ${name} deployed successfully!");
  console.log("Contract address:", address);
  console.log("Deployer address:", deployer.address);
  console.log("Transaction hash:", ${this._camelCase(name)}.deploymentTransaction().hash);

  // Verify contract on Etherscan (for mainnet/testnet)
  if (hre.network.name !== "hardhat" && hre.network.name !== "localhost") {
    console.log("\\nWaiting for block confirmations...");
    await ${this._camelCase(name)}.deploymentTransaction().wait(5);

    console.log("\\nVerifying contract on Etherscan...");
    try {
      await hre.run("verify:verify", {
        address: address,
        constructorArguments: [${this._getConstructorArgsList(name, specs, "ERC20")}],
      });
      console.log("Contract verified successfully!");
    } catch (error) {
      console.log("Contract verification failed:", error.message);
    }
  }

  // Save deployment info
  _saveDeploymentInfo({
    network: hre.network.name,
    contractName: "${name}",
    address: address,
    deployer: deployer.address,
    txHash: ${this._camelCase(name)}.deploymentTransaction().hash,
    timestamp: new Date().toISOString()
  });

  return ${this._camelCase(name)};
}

/**
 * Save deployment information to file
 */
function _saveDeploymentInfo(info) {
  const fs = require("fs");
  const path = require("path");

  const deploymentsDir = path.join(__dirname, "..", "deployments");
  if (!fs.existsSync(deploymentsDir)) {
    fs.mkdirSync(deploymentsDir, { recursive: true });
  }

  const filename = info.network + "-" + info.contractName + "-" + Date.now() + ".json";
  const filepath = path.join(deploymentsDir, filename);

  fs.writeFileSync(filepath, JSON.stringify(info, null, 2));
  console.log("Deployment info saved to:", filepath);
}

// Execute deployment
main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
`;
  }

  /**
   * 生成ERC721部署脚本
   */
  _generateERC721Deploy(name, specs = {}) {
    const args = this._getConstructorArgs(name, specs, "ERC721");

    return `const hre = require("hardhat");

/**
 * Deployment script for ${name}
 * Generated by Web3 AI Agent
 *
 * Usage: npx hardhat run scripts/deploy-${name}.js --network <network>
 */
async function main() {
  console.log("Deploying ${name}...");

  // Get deployer account
  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying contracts with account:", deployer.address);
  console.log("Account balance:", (await hre.ethers.provider.getBalance(deployer.address)).toString());

  // Deploy contract
  const ${this._camelCase(name)} = await hre.ethers.deployContract("${name}"${args});

  await ${this._camelCase(name)}.waitForDeployment();
  const address = await ${this._camelCase(name)}.getAddress();

  console.log("\\n✅ ${name} deployed successfully!");
  console.log("Contract address:", address);
  console.log("Deployer address:", deployer.address);
  console.log("Transaction hash:", ${this._camelCase(name)}.deploymentTransaction().hash);

  // Verify contract on Etherscan (for mainnet/testnet)
  if (hre.network.name !== "hardhat" && hre.network.name !== "localhost") {
    console.log("\\nWaiting for block confirmations...");
    await ${this._camelCase(name)}.deploymentTransaction().wait(5);

    console.log("\\nVerifying contract on Etherscan...");
    try {
      await hre.run("verify:verify", {
        address: address,
        constructorArguments: [${this._getConstructorArgsList(name, specs, "ERC721")}],
      });
      console.log("Contract verified successfully!");
    } catch (error) {
      console.log("Contract verification failed:", error.message);
    }
  }

  // Save deployment info
  _saveDeploymentInfo({
    network: hre.network.name,
    contractName: "${name}",
    address: address,
    deployer: deployer.address,
    txHash: ${this._camelCase(name)}.deploymentTransaction().hash,
    timestamp: new Date().toISOString()
  });

  return ${this._camelCase(name)};
}

/**
 * Save deployment information to file
 */
function _saveDeploymentInfo(info) {
  const fs = require("fs");
  const path = require("path");

  const deploymentsDir = path.join(__dirname, "..", "deployments");
  if (!fs.existsSync(deploymentsDir)) {
    fs.mkdirSync(deploymentsDir, { recursive: true });
  }

  const filename = info.network + "-" + info.contractName + "-" + Date.now() + ".json";
  const filepath = path.join(deploymentsDir, filename);

  fs.writeFileSync(filepath, JSON.stringify(info, null, 2));
  console.log("Deployment info saved to:", filepath);
}

// Execute deployment
main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
`;
  }

  /**
   * 生成DAO部署脚本
   */
  _generateDAODeploy(name, specs = {}) {
    return this._generateGenericDeploy(name);
  }

  /**
   * 生成投票部署脚本
   */
  _generateVotingDeploy(name, specs = {}) {
    return this._generateGenericDeploy(name);
  }

  /**
   * 生成通用部署脚本
   */
  _generateGenericDeploy(name) {
    return `const hre = require("hardhat");

/**
 * Deployment script for ${name}
 * Generated by Web3 AI Agent
 *
 * Usage: npx hardhat run scripts/deploy-${name}.js --network <network>
 */
async function main() {
  console.log("Deploying ${name}...");

  // Get deployer account
  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying contracts with account:", deployer.address);
  console.log("Account balance:", (await hre.ethers.provider.getBalance(deployer.address)).toString());

  // Deploy contract
  const ${this._camelCase(name)} = await hre.ethers.deployContract("${name}");

  await ${this._camelCase(name)}.waitForDeployment();
  const address = await ${this._camelCase(name)}.getAddress();

  console.log("\\n✅ ${name} deployed successfully!");
  console.log("Contract address:", address);
  console.log("Deployer address:", deployer.address);
  console.log("Transaction hash:", ${this._camelCase(name)}.deploymentTransaction().hash);

  // Verify contract on Etherscan (for mainnet/testnet)
  if (hre.network.name !== "hardhat" && hre.network.name !== "localhost") {
    console.log("\\nWaiting for block confirmations...");
    await ${this._camelCase(name)}.deploymentTransaction().wait(5);

    console.log("\\nVerifying contract on Etherscan...");
    try {
      await hre.run("verify:verify", {
        address: address,
        constructorArguments: [],
      });
      console.log("Contract verified successfully!");
    } catch (error) {
      console.log("Contract verification failed:", error.message);
    }
  }

  // Save deployment info
  _saveDeploymentInfo({
    network: hre.network.name,
    contractName: "${name}",
    address: address,
    deployer: deployer.address,
    txHash: ${this._camelCase(name)}.deploymentTransaction().hash,
    timestamp: new Date().toISOString()
  });

  return ${this._camelCase(name)};
}

/**
 * Save deployment information to file
 */
function _saveDeploymentInfo(info) {
  const fs = require("fs");
  const path = require("path");

  const deploymentsDir = path.join(__dirname, "..", "deployments");
  if (!fs.existsSync(deploymentsDir)) {
    fs.mkdirSync(deploymentsDir, { recursive: true });
  }

  const filename = info.network + "-" + info.contractName + "-" + Date.now() + ".json";
  const filepath = path.join(deploymentsDir, filename);

  fs.writeFileSync(filepath, JSON.stringify(info, null, 2));
  console.log("Deployment info saved to:", filepath);
}

// Execute deployment
main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
`;
  }

  /**
   * 获取构造函数参数
   */
  _getConstructorArgs(name, specs, type) {
    // ERC20和ERC721没有构造参数（在合约内部定义）
    return "";
  }

  /**
   * 获取构造函数参数列表（用于verify）
   */
  _getConstructorArgsList(name, specs, type) {
    return "";
  }

  /**
   * 转换为驼峰命名
   */
  _camelCase(str) {
    return str.charAt(0).toLowerCase() + str.slice(1);
  }

  /**
   * 确保目录存在
   */
  _ensureDir(dir) {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
  }
}

module.exports = DeployerAgent;
