// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title MyToken
 * @dev ERC20 Token Contract generated by Web3 AI Agent
 */
contract MyToken is ERC20, Ownable {
    constructor() ERC20("MyToken", "MYTO") {
        // Mint initial supply to deployer
        _mint(msg.sender, 1000000 * 10**18);
    }

    /**
     * @dev Mint new tokens (only owner)
     */
    function mint(address to, uint256 amount) public onlyOwner {
        _mint(to, amount);
    }

    /**
     * @dev Burn tokens
     */
    function burn(uint256 amount) public {
        _burn(msg.sender, amount);
    }

    /**
     * @dev Get token info
     */
    function getTokenInfo() external view returns (
        string memory name_,
        string memory symbol_,
        uint256 totalSupply_,
        uint256 decimals_
    ) {
        return (name(), symbol(), totalSupply(), decimals());
    }
}
