/**
 * Coder Agent - Generates Solidity Smart Contracts
 *
 * 功能：
 * - 接收planner生成的计划
 * - 生成对应的Solidity合约
 * - 保存到contracts/目录
 */

const fs = require("fs");
const path = require("path");

class CoderAgent {
  constructor(hre) {
    this.hre = hre;
    this.contractsDir = path.join(process.cwd(), "contracts");
  }

  /**
   * 根据计划生成Solidity合约
   * @param {object} plan - planner生成的执行计划
   * @returns {object} 生成结果
   */
  async generate(plan) {
    console.log("\n" + "=".repeat(70));
    console.log("💻 Coder Agent - Generating Solidity Contracts");
    console.log("=".repeat(70));

    try {
      // 确保contracts目录存在
      this._ensureDir(this.contractsDir);

      // 根据计划类型生成合约
      const contractCode = this._generateContractCode(plan);

      // 保存合约文件
      const fileName = `${plan.contractName}.sol`;
      const filePath = path.join(this.contractsDir, fileName);
      fs.writeFileSync(filePath, contractCode, "utf8");

      console.log(`\n✓ Contract generated: ${fileName}`);
      console.log(`  Location: contracts/${fileName}`);
      console.log(`  Size: ${contractCode.length} bytes`);

      return {
        success: true,
        fileName,
        filePath,
        contractName: plan.contractName,
        code: contractCode
      };

    } catch (error) {
      console.error(`\n✗ Error generating contract: ${error.message}`);
      return {
        success: false,
        error: error.message
      };
    }
  }

  /**
   * 生成合约代码
   * @param {object} plan - 执行计划
   * @returns {string} Solidity合约代码
   */
  _generateContractCode(plan) {
    const { contractName, type, features, specifications } = plan;

    // 根据合约类型生成不同的模板
    switch (type) {
      case "ERC20":
        return this._generateERC20(contractName, specifications);
      case "ERC721":
        return this._generateERC721(contractName, specifications);
      case "DAO":
        return this._generateDAO(contractName, specifications);
      case "Voting":
        return this._generateVoting(contractName, specifications);
      default:
        return this._generateGeneric(contractName, specifications);
    }
  }

  /**
   * 生成ERC20合约
   */
  _generateERC20(name, specs = {}) {
    const tokenName = specs.tokenName || name;
    const symbol = specs.symbol || name.substring(0, 4).toUpperCase();
    const supply = specs.initialSupply || "1000000";
    const decimals = specs.decimals || 18;

    return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title ${tokenName}
 * @dev ERC20 Token Contract generated by Web3 AI Agent
 */
contract ${name} is ERC20, Ownable {
    constructor() ERC20("${tokenName}", "${symbol}") {
        // Mint initial supply to deployer
        _mint(msg.sender, ${supply} * 10**${decimals});
    }

    /**
     * @dev Mint new tokens (only owner)
     */
    function mint(address to, uint256 amount) public onlyOwner {
        _mint(to, amount);
    }

    /**
     * @dev Burn tokens
     */
    function burn(uint256 amount) public {
        _burn(msg.sender, amount);
    }

    /**
     * @dev Get token info
     */
    function getTokenInfo() external view returns (
        string memory name_,
        string memory symbol_,
        uint256 totalSupply_,
        uint256 decimals_
    ) {
        return (name(), symbol(), totalSupply(), decimals());
    }
}
`;
  }

  /**
   * 生成ERC721合约
   */
  _generateERC721(name, specs = {}) {
    const tokenName = specs.tokenName || name;
    const symbol = specs.symbol || name.substring(0, 4).toUpperCase();
    const baseURI = specs.baseURI || "";

    return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title ${tokenName}
 * @dev ERC721 NFT Contract generated by Web3 AI Agent
 */
contract ${name} is ERC721, ERC721URIStorage, Ownable {
    uint256 private _tokenIdCounter;

    constructor() ERC721("${tokenName}", "${symbol}") {}

    /**
     * @dev Mint new NFT
     */
    function safeMint(address to, string memory uri) public onlyOwner returns (uint256) {
        uint256 tokenId = _tokenIdCounter++;
        _safeMint(to, tokenId);
        _setTokenURI(tokenId, uri);
        return tokenId;
    }

    /**
     * @dev Get token URI
     */
    function tokenURI(uint256 tokenId)
        public
        view
        override(ERC721, ERC721URIStorage)
        returns (string memory)
    {
        return super.tokenURI(tokenId);
    }

    /**
     * @dev Supports interface
     */
    function supportsInterface(bytes4 interfaceId)
        public
        view
        override(ERC721, ERC721URIStorage)
        returns (bool)
    {
        return super.supportsInterface(interfaceId);
    }

    /**
     * @dev Get total supply
     */
    function totalSupply() public view returns (uint256) {
        return _tokenIdCounter;
    }
}
`;
  }

  /**
   * 生成DAO合约
   */
  _generateDAO(name, specs = {}) {
    const quorum = specs.quorum || 51; // 百分比
    const votingPeriod = specs.votingPeriod || 7; // 天

    return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/security/ReentrancyGuard.sol";

/**
 * @title ${name}
 * @dev DAO Contract generated by Web3 AI Agent
 */
contract ${name} is Ownable, ReentrancyGuard {
    struct Proposal {
        uint256 id;
        address proposer;
        string description;
        uint256 voteCount;
        uint256 quorum;
        uint256 startTime;
        uint256 endTime;
        bool executed;
        mapping(address => bool) hasVoted;
    }

    uint256 private proposalCounter;
    mapping(uint256 => Proposal) public proposals;

    uint256 public quorumPercentage = ${quorum};
    uint256 public votingPeriod = ${votingPeriod} days;

    event ProposalCreated(uint256 indexed proposalId, address proposer, string description);
    event Voted(uint256 indexed proposalId, address voter, bool support);
    event ProposalExecuted(uint256 indexed proposalId);

    /**
     * @dev Create a new proposal
     */
    function createProposal(string memory description) external returns (uint256) {
        proposalCounter++;
        Proposal storage proposal = proposals[proposalCounter];

        proposal.id = proposalCounter;
        proposal.proposer = msg.sender;
        proposal.description = description;
        proposal.startTime = block.timestamp;
        proposal.endTime = block.timestamp + votingPeriod;
        proposal.quorum = (address(this).balance * quorumPercentage) / 100;

        emit ProposalCreated(proposalCounter, msg.sender, description);
        return proposalCounter;
    }

    /**
     * @dev Vote on a proposal
     */
    function vote(uint256 proposalId) external nonReentrant {
        Proposal storage proposal = proposals[proposalId];

        require(proposal.id != 0, "Proposal does not exist");
        require(!proposal.hasVoted[msg.sender], "Already voted");
        require(block.timestamp < proposal.endTime, "Voting ended");

        proposal.hasVoted[msg.sender] = true;
        proposal.voteCount++;

        emit Voted(proposalId, msg.sender, true);
    }

    /**
     * @dev Execute a proposal
     */
    function executeProposal(uint256 proposalId) external nonReentrant {
        Proposal storage proposal = proposals[proposalId];

        require(proposal.id != 0, "Proposal does not exist");
        require(!proposal.executed, "Already executed");
        require(block.timestamp >= proposal.endTime, "Voting not ended");
        require(proposal.voteCount >= proposal.quorum, "Quorum not reached");

        proposal.executed = true;
        emit ProposalExecuted(proposalId);
    }

    /**
     * @dev Get proposal details
     */
    function getProposal(uint256 proposalId) external view returns (
        uint256 id,
        address proposer,
        string memory description,
        uint256 voteCount,
        uint256 startTime,
        uint256 endTime,
        bool executed
    ) {
        Proposal storage proposal = proposals[proposalId];
        return (
            proposal.id,
            proposal.proposer,
            proposal.description,
            proposal.voteCount,
            proposal.startTime,
            proposal.endTime,
            proposal.executed
        );
    }
}
`;
  }

  /**
   * 生成投票合约
   */
  _generateVoting(name, specs = {}) {
    return this._generateDAO(name, specs);
  }

  /**
   * 生成通用合约
   */
  _generateGeneric(name, specs = {}) {
    return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title ${name}
 * @dev Contract generated by Web3 AI Agent
 */
contract ${name} is Ownable {
    // Add your contract logic here

    constructor() {
        // Initialize contract
    }

    // Add your functions here
}
`;
  }

  /**
   * 确保目录存在
   */
  _ensureDir(dir) {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
  }
}

module.exports = CoderAgent;
