const hre = require("hardhat");

/**
 * Deployment script for MyToken
 * Generated by Web3 AI Agent
 *
 * Usage: npx hardhat run scripts/deploy-MyToken.js --network <network>
 */
async function main() {
  console.log("Deploying MyToken...");

  // Get deployer account
  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying contracts with account:", deployer.address);
  console.log("Account balance:", (await hre.ethers.provider.getBalance(deployer.address)).toString());

  // Deploy contract
  const myToken = await hre.ethers.deployContract("MyToken");

  await myToken.waitForDeployment();
  const address = await myToken.getAddress();

  console.log("\n✅ MyToken deployed successfully!");
  console.log("Contract address:", address);
  console.log("Deployer address:", deployer.address);
  console.log("Transaction hash:", myToken.deploymentTransaction().hash);

  // Verify contract on Etherscan (for mainnet/testnet)
  if (hre.network.name !== "hardhat" && hre.network.name !== "localhost") {
    console.log("\nWaiting for block confirmations...");
    await myToken.deploymentTransaction().wait(5);

    console.log("\nVerifying contract on Etherscan...");
    try {
      await hre.run("verify:verify", {
        address: address,
        constructorArguments: [],
      });
      console.log("Contract verified successfully!");
    } catch (error) {
      console.log("Contract verification failed:", error.message);
    }
  }

  // Save deployment info
  _saveDeploymentInfo({
    network: hre.network.name,
    contractName: "MyToken",
    address: address,
    deployer: deployer.address,
    txHash: myToken.deploymentTransaction().hash,
    timestamp: new Date().toISOString()
  });

  return myToken;
}

/**
 * Save deployment information to file
 */
function _saveDeploymentInfo(info) {
  const fs = require("fs");
  const path = require("path");

  const deploymentsDir = path.join(__dirname, "..", "deployments");
  if (!fs.existsSync(deploymentsDir)) {
    fs.mkdirSync(deploymentsDir, { recursive: true });
  }

  const filename = info.network + "-" + info.contractName + "-" + Date.now() + ".json";
  const filepath = path.join(deploymentsDir, filename);

  fs.writeFileSync(filepath, JSON.stringify(info, null, 2));
  console.log("Deployment info saved to:", filepath);
}

// Execute deployment
main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
